trigger: none

pool: ubuntu-latest-publix

variables:
- name: DtlkRegionEast
  value: ent_dtlk
- name: DtlkRegionCentral
  value: entc_dtlk
  
stages:
- stage: Dev
  displayName: "Dev"
  jobs:
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'DEV_East'
      azdoEnvironment: DEV_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-dev'
      keyVaultName: 'cutdkyvtdbwss0tdpsxx01'
      patSecretName: 'cutddbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cutddbwstransp01'
      databricksHost: 'https://adb-3618393276190872.12.azuredatabricks.net/'
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'DEV_Central'
      azdoEnvironment: DEV_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-dev'
      keyVaultName: 'cutdkyvtdbwss0tdpsxx01'
      patSecretName: 'cucddbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cucddbwstransp01'
      databricksHost: 'https://adb-840646084492194.14.azuredatabricks.net/'
- stage: Tst
  displayName: "Tst"
  jobs:
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'TST_East'
      azdoEnvironment: TST_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-tst'
      keyVaultName: 'cuttkyvtdbwss0tdpsxx01'
      patSecretName: 'cuttdbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cuttdbwstransp01'
      databricksHost: 'https://adb-3674853172059167.7.azuredatabricks.net/'
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'TST_Central'
      azdoEnvironment: TST_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-tst'
      keyVaultName: 'cuttkyvtdbwss0tdpsxx01'
      patSecretName: 'cuctdbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cuctdbwstransp01'
      databricksHost: 'https://adb-1718286213798553.13.azuredatabricks.net/'
- stage: Stg
  displayName: "Stg"
  jobs:
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'STG_East'
      azdoEnvironment: STG_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-stg'
      keyVaultName: 'cutskyvtdbwss0tdpsxx01'
      patSecretName: 'cutsdbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cutsdbwstransp01'
      databricksHost: 'https://adb-3845968449054344.4.azuredatabricks.net/'
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'STG_Central'
      azdoEnvironment: STG_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-stg'
      keyVaultName: 'cutskyvtdbwss0tdpsxx01'
      patSecretName: 'cucsdbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cucsdbwstransp01'
      databricksHost: 'https://adb-4442784722564952.12.azuredatabricks.net/'
- stage: Prd
  displayName: "Prd"
  jobs:
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'PRD_East'
      azdoEnvironment: PRD_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-prd'
      keyVaultName: 'cutpkyvtdbwss0tdpsxx01'
      patSecretName: 'cutpdbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cutpdbwstransp01'
      databricksHost: 'https://adb-2699047964193452.12.azuredatabricks.net/'
  - template: Deploy_Template.yml
    parameters:
      publixEnvironment: 'PRD_Central'
      azdoEnvironment: PRD_S0TDPSXX
      azureSubscription: 's0tdpsxx-01-prd'
      keyVaultName: 'cutpkyvtdbwss0tdpsxx01'
      patSecretName: 'cucpdbwstransp01-databricks-pat'
      pythonVersion: '3.x'
      cli_version: 'v0.297.2'
      databricksUserAcct: 'cucpdbwstransp01'
      databricksHost: 'https://adb-987189095019215.15.azuredatabricks.net/'